language: python

python:
  - "3.9"

jobs:
  include:
    - name: Linter
      before_script:
        - pip install flake8
      script:
        - flake8 dhost --max-line-length 119 --per-file-ignores="__init__.py:F401" --ignore W391
    - name: Test
      script:
        - python manage.py test --parallel

