language: python
python:
  - "3.9"

jobs:
  include:
    - name: Linter
      before_script:
        - pip install flake8
      script:
        - flake8
    - name: Test
      script:
        - python manage.py test --parallel

