FROM python:3.9

EXPOSE 8000
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/
COPY requirements_dev.txt /app/
RUN pip install -r requirements.txt
RUN pip install -r requirements_dev.txt

ADD . /app/

RUN python manage.py migrate
RUN python manage.py collectstatic --no-input
RUN python manage.py loaddata ./dhost/demo/fixture.json

CMD ["gunicorn", "--bind", ":8000", "dhost.asgi:application", "--workers", "1", "--worker-class", "uvicorn.workers.UvicornWorker"]
