# Generated by Django 3.2.2 on 2021-05-18 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dapps', '0004_delete_bundle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLogEntry',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('action_flag',
                 models.PositiveSmallIntegerField(blank=True,
                                                  choices=[
                                                      (1, 'Addition'),
                                                      (2, 'Change'),
                                                      (3, 'Deletion'),
                                                      (4, 'Start build'),
                                                      (5, 'Build successful'),
                                                      (6, 'Build failed'),
                                                      (7, 'Start deployment'),
                                                      (8,
                                                       'Deployment successful'),
                                                      (9, 'Deployment failed')
                                                  ],
                                                  null=True)),
                ('change_message', models.TextField(blank=True)),
                ('action_time',
                 models.DateTimeField(default=django.utils.timezone.now,
                                      editable=False)),
                ('content_type',
                 models.ForeignKey(blank=True,
                                   null=True,
                                   on_delete=django.db.models.deletion.SET_NULL,
                                   to='contenttypes.contenttype')),
                ('dapp',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='dapps.dapp')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dashboard log entry',
                'verbose_name_plural': 'dashboard log entries',
                'ordering': ['-action_time'],
            },
        ),
    ]
