# Generated by Django 3.2.4 on 2021-06-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apilog',
            options={
                'ordering': ['-action_time'],
                'verbose_name': 'API log entry',
                'verbose_name_plural': 'API log entries'
            },
        ),
    ]
