# Generated by Django 3.2.4 on 2021-07-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apilog",
            name="action_flag",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("dapp_add", "Dapp created"),
                    ("dapp_change", "Dapp updated"),
                    ("bundle_add", "Bundle added"),
                    ("bundle_del", "Bundle removed"),
                    ("auto_deploy_start", "Auto deployment started"),
                    ("deploy_start", "Deployment started"),
                    ("deploy_success", "Deployment successful"),
                    ("deploy_fail", "Deployment failed"),
                    ("build_opt_add", "Build options created"),
                    ("build_opt_change", "Build options updated"),
                    ("build_opt_del", "Build options removed"),
                    ("auto_build_start", "Auto build started"),
                    ("build_start", "Build started"),
                    ("build_success", "Build successful"),
                    ("build_fail", "Build failed"),
                    ("env_var_add", "New environment variable"),
                    ("env_var_change", "Environment variable updated"),
                    ("env_var_del", "Environment variable removed"),
                    ("github_opt_add", "Github options created"),
                    ("github_opt_change", "Github options changed"),
                    ("github_opt_del", "Github options removed"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
