# Generated by Django 3.2.2 on 2021-06-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardlogentry',
            old_name='dapp',
            new_name='options',
        ),
    ]
