# Generated by Django 3.2.2 on 2021-06-07 13:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0001_initial'),
        ('logs', '0002_rename_dapp_dashboardlogentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardlogentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4,
                                   editable=False,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='dashboardlogentry',
            name='options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='logs',
                                    related_query_name='logs',
                                    to='dapps.dapp'),
        ),
    ]
