# Generated by Django 3.2.4 on 2021-06-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_apilog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='action_flag',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, 'Dapp created'), (2, 'Dapp updated'),
                         (4, 'Auto deployment started'),
                         (5, 'Deployment started'),
                         (6, 'Deployment successful'), (7, 'Deployment failed'),
                         (8, 'Build options created'),
                         (9, 'Build options updated'),
                         (10, 'Build options removed'),
                         (11, 'Auto build started'), (12, 'Build started'),
                         (13, 'Build successful'), (14, 'Build failed'),
                         (15, 'New environment variable'),
                         (16, 'Environment variable updated'),
                         (17, 'Environment variable removed')],
                null=True),
        ),
    ]
