# Generated by Django 3.2.5 on 2021-07-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_apilog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apilog',
            options={
                'ordering': ['-action_time'],
                'verbose_name': 'Dapp log entry',
                'verbose_name_plural': 'Dapp log entries'
            },
        ),
    ]
