# Generated by Django 3.2.5 on 2021-08-21 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dapps", "0003_alter_bundle_dapp"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logs", "0004_alter_apilog_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="APILog",
            new_name="DappLog",
        ),
    ]
