# Generated by Django 3.2b1 on 2021-05-18 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dapp',
            fields=[
                ('buildoptions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builds.buildoptions')),
                ('name', models.CharField(error_messages={'unique': 'A dapp with that name already exists.'}, max_length=128, unique=True, verbose_name='dapp name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('url', models.CharField(blank=True, max_length=2048, verbose_name='URL')),
                ('status', models.CharField(choices=[('SO', 'Stoped'), ('BI', 'Building'), ('BT', 'Builed'), ('DP', 'Deploying'), ('SA', 'Starting'), ('UP', 'Running'), ('UA', 'Unavailable'), ('ER', 'Error')], default='SO', max_length=2, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dapps', related_query_name='dapps', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'dapp',
                'verbose_name_plural': 'dapps',
                'abstract': False,
            },
            bases=('builds.buildoptions', models.Model),
        ),
    ]
