# Generated by Django 3.2.4 on 2021-06-06 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dapps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dapp',
            name='name',
        ),
        migrations.AlterField(
            model_name='dapp',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='dapps_dapp',
                                    related_query_name='dapps_dapp',
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='dapp',
            name='slug',
            field=models.SlugField(help_text='{user}/{slug}'),
        ),
        migrations.AddConstraint(
            model_name='dapp',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'),
                                               name='dapps_dapp_unique_slug'),
        ),
    ]
