# Generated by Django 3.1.6 on 2021-03-11 12:38

from django.db import migrations, models

import dhost.builds.models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='folder',
            field=models.FilePathField(allow_folders=True, blank=True, null=True, path=dhost.builds.models.bundle_path, verbose_name='folder'),
        ),
    ]
