# Generated by Django 3.2.4 on 2021-06-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dapp',
            name='slug',
            field=models.SlugField(help_text='[A-Za-z0-9_-]',
                                   max_length=256,
                                   verbose_name='dapp name'),
        ),
    ]
