# Generated by Django 3.1.6 on 2021-03-10 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='dapp',
            name='created',
        ),
        migrations.AddField(
            model_name='dapp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='dapp',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
