# Generated by Django 3.2.4 on 2021-06-21 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dapps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dapp",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created at"
            ),
        ),
    ]
