# Generated by Django 3.2b1 on 2021-03-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0002_auto_20210311_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='build',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='dapp',
        ),
    ]
