# Generated by Django 3.2.4 on 2021-06-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_auto_20210611_1648'),
        ('dapps', '0002_dapp_github_repo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dapp',
            name='github_repo',
        ),
        migrations.CreateModel(
            name='DappGithubRepo',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('auto_deploy',
                 models.BooleanField(
                     default=False,
                     help_text=
                     'Automaticaly deploy the dapp when a webhook is called.')),
                ('confirm_ci',
                 models.BooleanField(
                     default=False,
                     help_text=
                     'Wait for CI to be done before deploying the dapp whenauto deploy is on.'
                 )),
                ('branch',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.SET_NULL,
                                   to='github.branch')),
                ('dapp',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='github_repo',
                     related_query_name='github_repo',
                     to='dapps.dapp')),
                ('repo',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='github.repository')),
            ],
            options={
                'verbose_name': 'Dapp Github repository',
                'verbose_name_plural': 'Dapp Github repositories',
            },
        ),
    ]
