# Generated by Django 3.2.5 on 2021-09-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dapps", "0003_alter_bundle_dapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundle",
            name="folder",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="folder path",
            ),
        ),
    ]
