# Generated by Django 3.2b1 on 2021-03-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0003_auto_20210312_1155'),
        ('ipfs', '0003_alter_ipfsdeployment_bundle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundle',
        ),
    ]
