# Generated by Django 4.0.3 on 2022-03-10 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dapps", "0004_alter_bundle_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dapp",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                related_query_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
    ]
