# Generated by Django 4.0 on 2021-12-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210730_0819'),
        ('dapps', '0004_alter_bundle_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dapp',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', related_query_name='%(app_label)s_%(class)s', to='users.user', verbose_name='owner'),
        ),
    ]
