# Generated by Django 4.0.3 on 2022-04-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dapps", "0006_alter_dapp_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundle",
            name="folder_tree",
            field=models.TextField(
                blank=True, null=True, verbose_name="folder tree"
            ),
        ),
    ]
