# Generated by Django 4.0.3 on 2022-03-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dapps", "0006_bundle_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bundle",
            name="media",
        ),
    ]
