# Generated by Django 4.0.3 on 2022-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dapps", "0008_bundle_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundle",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
