# Generated by Django 3.2.4 on 2021-07-06 09:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('subject',
                 models.CharField(max_length=200, verbose_name='subject')),
                ('content',
                 models.TextField(max_length=10000, verbose_name='content')),
                ('read', models.BooleanField(default=False,
                                             verbose_name='read')),
                ('url',
                 models.URLField(blank=True, null=True, verbose_name='URL')),
                ('time',
                 models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='notifications',
                                   related_query_name='notifications',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
            },
        ),
    ]
