# Generated by Django 3.2.4 on 2021-06-10 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('github_id', models.IntegerField()),
                ('github_owner', models.CharField(max_length=256)),
                ('github_repo', models.CharField(max_length=256)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('added',
                 models.DateTimeField(auto_now_add=True,
                                      help_text='Added at.')),
                ('updated',
                 models.DateTimeField(
                     default=django.utils.timezone.now,
                     help_text='Last updated from the Github API.')),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='github_repos',
                                   related_query_name='github_repos',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Github repository',
                'verbose_name_plural': 'Github repositories',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('github_id', models.IntegerField()),
                ('name', models.CharField(default='web', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('added',
                 models.DateTimeField(auto_now_add=True,
                                      help_text='Added at.')),
                ('modified',
                 models.DateTimeField(
                     default=django.utils.timezone.now,
                     help_text='Last updated from the Github API.')),
                ('last_called',
                 models.DateTimeField(blank=True,
                                      help_text='Last called by Github.',
                                      null=True)),
                ('repo',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='webhooks',
                                   related_query_name='webhooks',
                                   to='github.repository')),
            ],
            options={
                'verbose_name': 'Github webhook',
                'verbose_name_plural': 'Github webhooks',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True)),
                ('repo',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='branches',
                                   related_query_name='branches',
                                   to='github.repository')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
