# Generated by Django 3.2.2 on 2021-06-02 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepo',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('branch', models.CharField(default='main', max_length=256)),
                ('size', models.SmallIntegerField(blank=True, null=True)),
                ('auto_deploy', models.BooleanField(default=False)),
                ('updated',
                 models.DateTimeField(
                     blank=True,
                     editable=False,
                     help_text='Last updated from external source.',
                     null=True)),
                ('created',
                 models.DateTimeField(auto_now_add=True,
                                      help_text='Created at.')),
                ('modified',
                 models.DateTimeField(
                     auto_now=True,
                     help_text='Last modified by user or external source.')),
                ('github_owner', models.CharField(max_length=256)),
                ('github_repo', models.CharField(max_length=256)),
                ('github_extra_data', models.JSONField(blank=True, null=True)),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='social_django.usersocialauth')),
            ],
            options={
                'verbose_name': 'Github repository',
                'verbose_name_plural': 'Github repositories',
                'abstract': False,
            },
        ),
    ]
