# Generated by Django 3.2.5 on 2021-09-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Raw response from the Github API.",
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Raw response from the Github API.",
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Raw response from the Github API.",
            ),
        ),
    ]
