# Generated by Django 3.2.4 on 2021-06-10 07:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepo',
            old_name='github_extra_data',
            new_name='extra_data',
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='auto_deploy',
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='size',
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='updated',
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='added',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now,
                                       help_text='Added at.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='modified',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text='Last updated from the Github API.'),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='github_repos',
                                    related_query_name='github_repos',
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name='owner'),
        ),
        migrations.CreateModel(
            name='GithubWebhooks',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('github_id', models.IntegerField()),
                ('name', models.CharField(default='web', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('added',
                 models.DateTimeField(auto_now_add=True,
                                      help_text='Added at.')),
                ('modified',
                 models.DateTimeField(
                     default=django.utils.timezone.now,
                     help_text='Last updated from the Github API.')),
                ('last_called',
                 models.DateTimeField(blank=True,
                                      help_text='Last called by Github.',
                                      null=True)),
                ('repo',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='webhooks',
                                   related_query_name='webhooks',
                                   to='github.githubrepo')),
            ],
            options={
                'verbose_name': 'Github webhook',
                'verbose_name_plural': 'Github webhooks',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True)),
                ('repo',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='branches',
                                   related_query_name='branches',
                                   to='github.githubrepo')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
