# Generated by Django 3.2.4 on 2021-06-11 16:48

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='added',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='webhook',
            old_name='added',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='webhook',
            old_name='last_called',
            new_name='last_called_at',
        ),
        migrations.RenameField(
            model_name='webhook',
            old_name='modified',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='github_id',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='github_id',
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last updated from the Github API.'),
        ),
        migrations.AddField(
            model_name='repository',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repository',
            name='id',
            field=models.IntegerField(help_text='Github repository unique ID.', primary_key=True, serialize=False, unique=True, verbose_name='Github ID'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='id',
            field=models.IntegerField(help_text='Github webhook unique ID.', primary_key=True, serialize=False, unique=True, verbose_name='Github ID'),
        ),
    ]
