# Generated by Django 3.1.6 on 2021-03-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='dapp',
        ),
    ]
