# Generated by Django 3.2.2 on 2021-05-30 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github', '0002_auto_20210312_1929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Github',
            new_name='GithubRepository',
        ),
        migrations.AlterModelOptions(
            name='githubrepository',
            options={'verbose_name': 'Github repository', 'verbose_name_plural': 'Github repositories'},
        ),
    ]
