# Generated by Django 3.2.4 on 2021-06-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_auto_20210610_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepo',
            old_name='modified',
            new_name='updated',
        ),
    ]
