# Generated by Django 3.2.5 on 2021-07-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.AddField(
            model_name="user",
            name="gravatar_hash",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
