# Generated by Django 3.2.4 on 2021-06-17 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPFSDapp',
            fields=[
                ('dapp_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='dapps.dapp')),
                ('ipfs_hash',
                 models.CharField(blank=True,
                                  max_length=128,
                                  verbose_name='IPFS hash')),
                ('ipfs_gateway',
                 models.URLField(blank=True,
                                 default='https://ipfs.io/ipfs/',
                                 null=True,
                                 verbose_name='IPFS public gateway')),
            ],
            options={
                'verbose_name': 'IPFS Dapp',
                'verbose_name_plural': 'IPFS Dapps',
            },
            bases=('dapps.dapp',),
        ),
        migrations.CreateModel(
            name='IPFSDeployment',
            fields=[
                ('deployment_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='dapps.deployment')),
                ('ipfs_hash',
                 models.CharField(blank=True,
                                  max_length=128,
                                  verbose_name='IPFS hash')),
            ],
            options={
                'verbose_name': 'IPFS Deployment',
                'verbose_name_plural': 'IPFS Deployments',
            },
            bases=('dapps.deployment',),
        ),
    ]
