# Generated by Django 3.1.6 on 2021-03-11 09:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPFSDapp',
            fields=[
                ('dapp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dapps.dapp')),
                ('hash', models.CharField(blank=True, max_length=128, verbose_name='IPFS hash')),
            ],
            options={
                'verbose_name': 'dapp',
                'verbose_name_plural': 'dapps',
                'abstract': False,
            },
            bases=('dapps.dapp',),
        ),
        migrations.CreateModel(
            name='IPFSDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SO', 'Stoped'), ('DP', 'Deploying'), ('SA', 'Starting'), ('UP', 'Running'), ('UA', 'Unavailable')], default='SO', max_length=2)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(null=True)),
                ('hash', models.CharField(blank=True, max_length=128, verbose_name='IPFS hash')),
                ('bundle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', related_query_name='deployments', to='dapps.bundle')),
                ('dapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', related_query_name='deployments', to='ipfs.ipfsdapp', verbose_name='dapp')),
            ],
            options={
                'verbose_name': 'deployment',
                'verbose_name_plural': 'deployments',
                'abstract': False,
            },
        ),
    ]
