# Generated by Django 3.2.2 on 2021-05-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipfsdapp',
            name='ipfs_gateway',
            field=models.URLField(blank=True,
                                  default='https://ipfs.io/ipfs/',
                                  null=True,
                                  verbose_name='IPFS public gateway'),
        ),
    ]
