# Generated by Django 3.1.6 on 2021-03-10 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipfsdapp',
            name='hash',
            field=models.CharField(max_length=128, verbose_name='IPFS hash'),
        ),
        migrations.AlterField(
            model_name='ipfsdeployment',
            name='dapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', related_query_name='deployments', to='ipfs.ipfsdapp', verbose_name='dapp'),
        ),
    ]
