# Generated by Django 3.2.2 on 2021-06-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipfs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipfsdapp',
            old_name='hash',
            new_name='ipfs_hash',
        ),
        migrations.RenameField(
            model_name='ipfsdeployment',
            old_name='hash',
            new_name='ipfs_hash',
        ),
    ]
