# Generated by Django 4.0.3 on 2022-03-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipfs", "0002_ipfsfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IPFSFile",
        ),
    ]
