# Generated by Django 3.2b1 on 2021-03-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_auto_20210311_1238'),
        ('ipfs', '0002_auto_20210311_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipfsdeployment',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', related_query_name='deployments', to='builds.bundle'),
        ),
    ]
