# Generated by Django 3.1.6 on 2021-03-10 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import dhost.builds.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FilePathField(allow_files=False, allow_folders=True, help_text='Source folder', max_length=1024, null=True, path=dhost.builds.models.source_path, recursive=True)),
                ('command', models.CharField(help_text='Command used during the build process.', max_length=2048, verbose_name='build command')),
                ('docker_container', models.CharField(blank=True, help_text='Container used for the build process', max_length=128)),
            ],
            options={
                'verbose_name': 'build options',
                'verbose_name_plural': 'builds options',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=1024)),
                ('value', models.CharField(max_length=8192)),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envars', to='builds.buildoptions')),
            ],
            options={
                'verbose_name': 'environment variable',
                'verbose_name_plural': 'environment variables',
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, help_text='Build number')),
                ('is_success', models.BooleanField(help_text='Based on the build return code', null=True)),
                ('logs', models.TextField(help_text='Raw logs output of the build process')),
                ('source', models.FilePathField(allow_files=False, allow_folders=True, help_text='Source folder', max_length=1024, null=True, path=dhost.builds.models.source_path, recursive=True)),
                ('bundle', models.FilePathField(allow_files=False, allow_folders=True, help_text='Bundle folder', max_length=1024, null=True, path=dhost.builds.models.bundle_path, recursive=True)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(null=True)),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', related_query_name='builds', to='builds.buildoptions')),
            ],
            options={
                'verbose_name': 'build',
                'verbose_name_plural': 'builds',
                'unique_together': {('options', 'number')},
            },
        ),
    ]
