# Generated by Django 3.1.6 on 2021-03-11 12:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import dhost.builds.models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder', models.FilePathField(allow_folders=True, blank=True, null=True, path=dhost.builds.models.bundle_path, verbose_name='folder')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'bundle',
                'verbose_name_plural': 'bundles',
            },
        ),
        migrations.RenameField(
            model_name='build',
            old_name='source',
            new_name='source_path',
        ),
        migrations.AlterField(
            model_name='buildoptions',
            name='source',
            field=models.FilePathField(allow_folders=True, blank=True, max_length=1024, null=True, path=dhost.builds.models.source_path, recursive=True, verbose_name='Source folder'),
        ),
        migrations.AlterField(
            model_name='build',
            name='bundle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builds.bundle', verbose_name='bundle'),
        ),
    ]
