# Generated by Django 3.1.6 on 2021-03-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildoptions',
            old_name='docker_container',
            new_name='docker',
        ),
        migrations.AlterField(
            model_name='build',
            name='is_success',
            field=models.BooleanField(blank=True, help_text='Based on the build return code', null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='logs',
            field=models.TextField(blank=True, help_text='Raw logs output of the build process'),
        ),
    ]
