# Generated by Django 3.2.5 on 2021-08-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="envvar",
            name="sensitive",
            field=models.BooleanField(default=False),
        ),
    ]
