# Generated by Django 3.2b1 on 2021-03-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_auto_20210311_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildoptions',
            name='id',
            field=models.BigAutoField(auto_created=True,
                                      primary_key=True,
                                      serialize=False,
                                      verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='id',
            field=models.BigAutoField(auto_created=True,
                                      primary_key=True,
                                      serialize=False,
                                      verbose_name='ID'),
        ),
    ]
