# Generated by Django 3.2.5 on 2021-08-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0002_envvar_sensitive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envvar",
            name="sensitive",
            field=models.BooleanField(
                default=False, help_text="Hide the value if set."
            ),
        ),
    ]
