# Generated by Django 3.2.2 on 2021-06-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_alter_environmentvariable_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentvariable',
            name='variable',
            field=models.SlugField(max_length=1024),
        ),
    ]
