# Generated by Django 3.2b1 on 2021-03-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_auto_20210312_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildoptions',
            name='docker',
            field=models.CharField(
                blank=True,
                help_text='Container used for the build process.',
                max_length=128),
        ),
    ]
