# Generated by Django 3.2b1 on 2021-03-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_alter_buildoptions_docker'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='options',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='bundles',
                                    related_query_name='bundles',
                                    to='builds.buildoptions'),
        ),
        migrations.AlterField(
            model_name='build',
            name='bundle',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='build',
                related_query_name='build',
                to='builds.bundle',
                verbose_name='bundle'),
        ),
    ]
