version: "3.7"

services:
  api:
    build:
      context: ./../../
      dockerfile: ./tools/docker/api/Dockerfile_dev
    restart: unless-stopped
    volumes:
      - ./../../:/app
    ports:
      - 8000:8000
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,api
      - DJANGO_ENV=development  # can be set to `production`
      - DJANGO_SECRET_KEY=secret
      - ENABLE_SSL=False

  dashboard:
    build:
      context: ./../../dhost/frontend/
    restart: unless-stopped
    volumes:
      - ./../../dhost/frontend/:/app
      - /app/node_modules/
    ports:
      - 3000:3000

#  build-microservice:
#    build:
#      context: ./build-microservice
#    restart: unless-stopped
#    ports:
#      - 5000:5000
#    environment:
#      - FLASK_ENV=development
#      - HOST=0.0.0.0
