version: "3.7"

services:
  api:
    build:
      context: ./../../
      dockerfile: ./tools/docker/api/Dockerfile_dev
    restart: unless-stopped
    volumes:
      - ./../../:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,api
      - DJANGO_ENV=development  # can be set to `production`
      - DJANGO_SECRET_KEY=secret
      - ENABLE_SSL=False
      - DATABASE_URL=postgres://dhost:dhost@db:5432/dhost
      - REDIS_URL=redis://redis:6379/1  # used for django cache
      - EMAIL_HOST=mailhog
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  celery:
    build:
      context: ./../../
      dockerfile: ./tools/docker/api/Dockerfile_dev
    command: celery -A dhost worker --loglevel=info
    volumes:
      - ./../../:/app
    depends_on:
      - api
      - redis
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,celery
      - DJANGO_ENV=development  # can be set to `production`
      - DJANGO_SECRET_KEY=secret
      - ENABLE_SSL=False
      - REDIS_URL=redis://redis:6379/1  # used for django cache
      - EMAIL_HOST=mailhog
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  dashboard:
    build:
      context: ./../../dhost/frontend/
    restart: unless-stopped
    volumes:
      - ./../../dhost/frontend/:/app
      - /app/node_modules/
    ports:
      - 3000:3000

#  build-microservice:
#    build:
#      context: ./build-microservice
#    restart: unless-stopped
#    ports:
#      - 5000:5000
#    environment:
#      - FLASK_ENV=development
#      - HOST=0.0.0.0

#  docusaurus:
#    build:
#      context: ./dhost-doc
#    restart: unless-stopped
#    volumes:
#      - ./dhost-doc/:/app
#      - /app/node_modules/
#    ports:
#      - 3003:3000

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dhost
      - POSTGRES_PASSWORD=dhost

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    restart: unless-stopped
