name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prod:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: dhost
          POSTGRES_PASSWORD: dhost
          POSTGRES_DB: dhost
        ports:
          - 5432:5432
    env:
      DEBUG: "False"
      DATABASE_URL: "postgres://dhost:dhost@127.0.0.1:5432/dhost"
      SECRET_KEY: verysecretkey
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Collect static
      run: |
        python manage.py collectstatic
    - name: Run Tests
      run: |
        python manage.py test --parallel
