name: Lint

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install isort
        pip install flake8
    - name: Analysing the code with black
      run: black --check .
    - name: Order import with isort
      run: isort .
    - name: Lint with flake8
      run: flake8 .
