name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
        name: Test Docker
        command: |
          docker run

